INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Red pública','',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Red pública',' ',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Red pública',' ',' ','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otro',' ',' ','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','Si','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','Si','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','No','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','Si','Si','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','No','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','No','Por tubería fuera de la vivienda, lote o terreno');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','No','No','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Río, vertiente, acequia',' ',' ','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pozo',' ',' ','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','Si','Si','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','Si','No','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pozo',' ',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pozo',' ',' ','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Carro repartidor, triciclo',' ',' ','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otra fuente por tubería','Si','No','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Río, vertiente, acequia',' ',' ','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Carro repartidor, triciclo',' ',' ','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Carro repartidor, triciclo',' ',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pozo',' ',' ','Por tubería fuera de la vivienda, lote o terreno');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','No','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Red pública',' ',' ','Por tubería fuera de la vivienda, lote o terreno');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','No','Por tubería fuera de la vivienda, lote o terreno');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Río, vertiente, acequia',' ',' ','Por tubería fuera de la vivienda, lote o terreno');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','Si','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Río, vertiente, acequia',' ',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Red pública',' ',' ','No recibe agua por tubería sino por otros medios');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','No','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','No','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otro',' ',' ','Por tubería dentro de la vivienda');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Otro',' ',' ','Por tubería fuera de la vivienda pero en el lote');
INSERT INTO AGUA_VIVIENDA (fuente,medidor,obtencion_junta,recibe_vivienda) VALUES('Pila o llave pública','No','Si','Por tubería dentro de la vivienda');
