INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',160 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',170 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',350 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',240 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',350 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',125 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',300 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',260 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',300 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',220 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',700 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',600 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',300 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',180 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',230 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',90 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',175 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',195 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',165 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',70 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',180 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',450 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',20 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',300 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',220 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',350 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',450 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',230 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',180 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',420 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',220 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',190 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',310 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',260 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',65 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',40 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',600 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',300 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',140 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',280 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',350 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',225 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',450 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',1000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',85 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',380 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',380 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',260 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',270 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',430 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',360 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',70 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',999999 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',380 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',425 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',90 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',320 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',600 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',290 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',210 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',280 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',45 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',280 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',370 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',330 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',1000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',185 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',90 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',650 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',155 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',281 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',125 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',680 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',30 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',465 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',390 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',110 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',700 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',235 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',30 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',325 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',380 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',160 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',700 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',320 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',620 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',375 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',240 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',360 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',105 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',360 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',70 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',40 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',75 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',20 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',40 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',55 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',10 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',140 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',110 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',160 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',30 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',20 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',35 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',170 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',30 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',280 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',140 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',110 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',135 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',20 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',125 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',25 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',5000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',70 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',24 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',170 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',145 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',320 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',40 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',15 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',25 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',70 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',25 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',90 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',270 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',95 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',180 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',190 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',145 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',115 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',180 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',110 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',25 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',75 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',240 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',2000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',1000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',1500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',550 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',600 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',650 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',175 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',1500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',1000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',110 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',210 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',170 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',750 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',265 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',2000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',550 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',156 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',140 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',54 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',240 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',160 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',10 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',150 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',90 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',285 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',220 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',155 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',120 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',50 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',60 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Otra',200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',315 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',178 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',440 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',125 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',3000 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',340 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',275 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',35 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',187 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',215 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',83 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',65 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',520 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',85 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',850 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',900 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',2500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',3500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',2500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',650 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',660 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',2800 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',2500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',1200 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',1500 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',750 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',15 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',78 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',350 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',80 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',30 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',96 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',21 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',228 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',65 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',15 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',20 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',35 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',310 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',999999 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',100 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',262 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',480 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',340 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',650 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',67 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',550 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',470 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',470 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',450 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',114 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',250 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',405 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',130 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',116 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',158 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',15 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',75 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',220 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Anticresis y/o arriendo',700 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',10 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',279 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',1600 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',82 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',104 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',230 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',245 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',230 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',190 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',137 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',115 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',470 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',999999 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',99999 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('En arriendo',126 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Recibida por servicios',400 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Cedida',175 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y la está pagando',40 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',45 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',55 );
INSERT INTO PROPIEDAD_VIVIENDA (manera_tenencia,valor_pago_mensual_total) VALUES('Propia y totalmente pagada',12 );
